version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:3.6.3-jessie
    volumes:
      - ./data:/data/d
    ports:
      - "27017:27017"